/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/6849947d3fd646e4c15bec8b.glb -t -o src/components/Avatar.tsx -r public 
*/

import * as THREE from "three";
import React, { JSX, useEffect, useMemo, useRef, useState } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { GLTF, SkeletonUtils } from "three-stdlib";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

type GLTFAction = THREE.AnimationAction;

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh;
    Wolf3D_Glasses: THREE.SkinnedMesh;
    Wolf3D_Body: THREE.SkinnedMesh;
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh;
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh;
    Wolf3D_Outfit_Top: THREE.SkinnedMesh;
    EyeLeft: THREE.SkinnedMesh;
    EyeRight: THREE.SkinnedMesh;
    Wolf3D_Head: THREE.SkinnedMesh;
    Wolf3D_Teeth: THREE.SkinnedMesh;
    Wolf3D_Beard: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial;
    Wolf3D_Glasses: THREE.MeshStandardMaterial;
    Wolf3D_Body: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial;
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial;
    Wolf3D_Eye: THREE.MeshStandardMaterial;
    Wolf3D_Skin: THREE.MeshStandardMaterial;
    Wolf3D_Teeth: THREE.MeshStandardMaterial;
    Wolf3D_Beard: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Avatar(props: JSX.IntrinsicElements["group"]) {
  const [animation, setAnimation] = useState("ThoughtfulHeadNod");

  const { playAudio, script } = useControls({
    playAudio: false,
    script: {
      value: "test",
      options: ["test"],
    },
  });

  const audio = useMemo(() => new Audio(`/Audio/${script}.wav`), [script]);

  useFrame(() => {
    if (audio.paused || audio.ended) {
      setAnimation("Idle");
    }
  });

  useEffect(() => {
    if (playAudio) {
      setAnimation("TalkingPoseTwo");
      audio.play();
    } else {
      setAnimation("Waving");
      audio.pause();
    }
  }, [playAudio, script]);

  const group = useRef<THREE.Group>(null!);
  const { scene } = useGLTF("/Models/6849947d3fd646e4c15bec8b.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;

  const { animations: acknowledging } = useFBX("/Animations/Acknowledging.fbx");
  const { animations: idle } = useFBX("/Animations/Idle.fbx");
  const { animations: talking } = useFBX("/Animations/Talking.fbx");
  const { animations: talking2 } = useFBX("/Animations/TalkingPoseTwo.fbx");
  const { animations: headNod } = useFBX("/Animations/ThoughtfulHeadNod.fbx");
  const { animations: waving } = useFBX("/Animations/Waving.fbx");
  const { animations: wheelbarrowIdle } = useFBX(
    "/Animations/WheelbarrowIdle.fbx"
  );

  // assegna i nomi
  acknowledging[0].name = "Acknowledging";
  idle[0].name = "Idle";
  talking[0].name = "Talking";
  talking2[0].name = "TalkingPoseTwo";
  headNod[0].name = "ThoughtfulHeadNod";
  waving[0].name = "Waving";
  wheelbarrowIdle[0].name = "WheelbarrowIdle";

  const { actions } = useAnimations(
    [
      acknowledging[0],
      idle[0],
      talking[0],
      talking2[0],
      headNod[0],
      waving[0],
      wheelbarrowIdle[0],
    ],
    group
  );

  useEffect(() => {
    if (!animation || !actions[animation]) return;

    actions[animation].reset().fadeIn(0.5).play();
    return () => {
      actions[animation]?.fadeOut(0.5);
    };
  }, [animation]);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Beard"
        geometry={nodes.Wolf3D_Beard.geometry}
        material={materials.Wolf3D_Beard}
        skeleton={nodes.Wolf3D_Beard.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Beard.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Beard.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/Models/6849947d3fd646e4c15bec8b.glb");
